mode = "All-to-all"

# [ping]
# packet_count = 3
# size = 48

# [http]
# path = "/"
# header_bytes = 0
# port = 80
# version = 1.1
# method = "GET"

[traceroute]
protocol = "TCP"
packets = 3
size = 48
first_hop = 1
max_hops = 32
paris = 16
dont_fragment = false
port = 80

# [probes]
# probes = [
#     6562,
#     7075
# ]

[anchors]
anchors = [
    1523,
    3042,
]
